sudo: required
dist: trusty

language: cpp

compiler: gcc

before_install:
  - export CXX="g++-4.9"
  - g++-4.9 --version

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake -Dexample:bool=on ..
#  - cmake -Dexamples:bool=on .. # cannot build GUI example

script:
  - cd $TRAVIS_BUILD_DIR
  - cd build
  - make -j$(nproc)

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - libboost-system-dev
#      - libwxgtk3.0-dev # still not working
