sudo: false

language: cpp

compiler: gcc

before_install:
  - export cwd=$(pwd)

before_script:
  - cd $cwd
  - mkdir build && cd build
  - cmake ..

script:
  - cd $cwd
  - cd build
  - make -j$(nproc)

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest-ppa
    packages:
      - g++-4.9
      - libboost1.55-dev
