language: cpp

compiler: gcc

before_install:
  - export cwd=$(pwd)
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get update
  - sudo apt-get install g++-4.9
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
  - sudo apt-get install libboost1.55-dev

before_script:
  - cd $cwd
  - mkdir build && cd build
  - cmake ..

script:
  - cd $cwd
  - cd build
  - make -j$(nproc)
